name: Build Noor-ul-Huda APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        
    - name: Create Flutter Project
      run: |
        # Remove existing Flutter folders
        rm -rf android ios lib test
        
        # Create new Flutter project
        flutter create --org com.noorulhuda --project-name noor_ul_huda_app .
        
    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: noor-ul-huda-app
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
